# Generated by Django 2.0.1 on 2018-01-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(default='Unnamed Location', max_length=80)),
                ('description', models.TextField(blank=True, max_length=6144)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='locations.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='link', to='locations.Place')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(default='Unnamed Location', max_length=80)),
                ('description', models.TextField(blank=True, max_length=6144)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='locations.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='link', to='locations.Region')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='region',
            name='peers',
            field=models.ManyToManyField(related_name='_region_peers_+', through='locations.RegionLink', to='locations.Region'),
        ),
        migrations.AddField(
            model_name='place',
            name='peers',
            field=models.ManyToManyField(related_name='_place_peers_+', through='locations.PlaceLink', to='locations.Place'),
        ),
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='regionlink',
            unique_together={('source', 'destination')},
        ),
        migrations.AlterUniqueTogether(
            name='placelink',
            unique_together={('source', 'destination')},
        ),
    ]
