# Generated by Django 2.0.1 on 2018-02-08 04:43

import core.characters.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180201_0722'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('lastOn', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(default='acct0/avatar_null.png', upload_to=core.characters.models.Character.get_avatar_name)),
                ('title', models.CharField(blank=True, default='Citizen', max_length=24)),
                ('name', models.CharField(default='John Doe', max_length=24)),
                ('age', models.PositiveIntegerField(default=7670)),
                ('height', models.PositiveSmallIntegerField(default=170)),
                ('sex', models.CharField(default='', max_length=8)),
                ('race', models.CharField(blank=True, default='Human', max_length=24)),
                ('biography', models.CharField(blank=True, default='', max_length=10240)),
                ('shortDesc', models.CharField(blank=True, default='A nondescript human specimen.', max_length=256)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='accounts.Account')),
                ('homePlace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inhabitants', to='locations.Place')),
                ('homeRegion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='natives', to='locations.Region')),
                ('lastPlace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hereNow', to='locations.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hitpoints', models.PositiveIntegerField(default=0)),
                ('hitpointsMax', models.PositiveIntegerField(default=0)),
                ('stamina', models.PositiveIntegerField(default=10000)),
                ('staminaMax', models.PositiveIntegerField(default=10000)),
                ('attack', models.PositiveIntegerField(default=0)),
                ('defense', models.PositiveIntegerField(default=0)),
                ('mana', models.PositiveIntegerField(default=0)),
                ('money', models.PositiveIntegerField(default=0)),
                ('carryWeight', models.PositiveIntegerField(default=0)),
                ('carryBulk', models.PositiveIntegerField(default=0)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats+', to='characters.Character')),
            ],
        ),
    ]
